const types = {
  LOGIN_SUCESS: 'LOGIN_SUCESS',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  PERSIST_REHYDRATE: 'persist/REHYDRATE',

  REGISTER_CREATED_SUCESS: 'REGISTER_CREATED_SUCESS',
  REGISTER_UPDATED_SUCESS: 'REGISTER_UPDATED_SUCESS',
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
};

export default types;
